package com.stablecoin.custody.fireblocks.domain.audit

enum class AuditOperation {
    VAULT_CREATED,
    VAULT_CREATION_FAILED,
    ASSET_ACTIVATED,
    ADDRESS_GENERATED,
    TRANSACTION_SUBMITTED,
    TRANSACTION_STATUS_UPDATED,
    TRANSACTION_SUBMISSION_FAILED,
    WEBHOOK_RECEIVED,
    WEBHOOK_VERIFICATION_FAILED,
    BALANCE_QUERIED,
    FEE_ESTIMATED,
    TRANSACTION_CANCELLATION_REQUESTED,
    TRANSACTION_CANCELLATION_REJECTED,
    ALLOCATION_LOCKED,
    ALLOCATION_RELEASED,
    ALLOCATION_CONSUMED,
    ALLOCATION_RELEASED_BY_CLEANUP,
    ALLOCATION_FAILED_BY_CLEANUP,
}
