spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085
  kafka:
    consumer:
      auto-offset-reset: earliest

server:
  port: 0

management:
  server:
    port: -1
