spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085
  kafka:
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.stablecoin.custody.fireblocks.domain.event

rate-limit:
  capacity: 3
  refill-tokens: 3
  refill-duration: 1m

server:
  port: 0

management:
  server:
    port: -1

fireblocks:
  api:
    base-url: http://localhost:${wiremock.server.port:8089}
    connect-timeout: 5s
    read-timeout: 5s
  secrets:
    private-key-name: fireblocks/private-key
    api-key-name: fireblocks/api-key
    webhook-public-key-name: fireblocks/webhook-public-key

namastack:
  outbox:
    poll-interval: 100
    batch-size: 20
    jdbc:
      table-prefix: "custody_"
      schema-initialization:
        enabled: false
